CREATE TABLE movies (
    id INT AUTO_INCREMENT PRIMARY KEY,
    slug VARCHAR(255) UNIQUE,
    name VARCHAR(255),
    description TEXT,
    genres VARCHAR(255),
    rate DECIMAL(3, 1),
    length VARCHAR(20),
    img VARCHAR(255),
    INDEX idx_name (name),
    INDEX idx_genres (genres)
);


INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (1,'deadpool','Deadpool','A former Special Forces operative turned mercenary is subjected to a rogue experiment that leaves him with accelrated healing powers, adopting the alter ego Deadpool.','action,adventure,comedy',8.6,'1hr 48mins','deadpool.jpg');
INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (2,'we-are-the-millers','We''re the Millers','A veteran pot dealer creates a fake family as part of his plan to move a huge shipment of weed into the U.S. from Mexico.','adventure,comedy,crime',7.0,'1hr 50mins','we-are-the-millers.jpg');
INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (3,'straight-outta-compton','Straight Outta Compton','The group NWA emerges from the mean streets of Compton in Los Angeles, California, in the mid-1980s and revolutionizes Hip Hop culture with their music and tales about life in the hood.','biography,drama,history',8.0,'2hr 27mins','straight-outta-compton.jpg');
INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (4,'gridiron-gang','Gridiron Gang','Teenagers at a juvenile detention center, under the leadership of their counselor, gain self-esteem by playing football together.','crime,drama,sport',6.9,'2hr 5mins','gridiron-gang.jpg');
INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (5,'american-gangster','American Gangster','In 1970s America, a detective works to bring down the drug empire of Frank Lucas, a heroin kingpin from Manhattan, who is smuggling the drug into the country from the Far East.','biography,crime,drama',7.8,'2hr 37mins','american-gangster.jpg');
INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (6,'gangster-squad','Gangster Squad','It''s 1949 Los Angeles, the city is run by gangsters and a malicious mobster, Micslug Cohen. Determined to end the corruption, John O''Mara assembles a team of cops, ready to take down the ruthless leader and restore peace to the city.','action,crime,drama',6.8,'1hr 53mins','gangster-squad.jpg');
INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (7,'now-you-see-me','Now You See Me','An FBI agent and an Interpol detective track a team of illusionists who pull off bank heists during their performances and reward their audiences with the money.','crime,mystery,thriller',7.3,'1hr 55mins','now-you-see-me.jpg');
INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (8,'jurassic-world','Jurassic World','A new theme park is built on the original site of Jurassic Park. Everything is going well until the park''s newest attraction--a genetically modified giant stealth killing machine--escapes containment and goes on a killing spree.','action,adventure,scifi',7.1,'2hr 4mins','jurassic-world.jpg');
INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (9,'mission-impossible-rogue-nation','Mission: Impossible: Rogue Nation','Ethan and team take on their most impossible mission yet, eradicating the Syndicate - an International rogue organization as highly skilled as they are, committed to destroying the IMF.','action,adventure,thriller',7.5,'2hr 11mins','mission-impossible-rogue-nation.jpg');
INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (10,'the-man-from-uncle','The Man from U.N.C.L.E.','In the early 1960s, CIA agent Napoleon Solo and KGB operative Illya Kuryakin participate in a joint mission against a mysterious criminal organization, which is working to proliferate nuclear weapons.','action,adventure,thriller',7.3,'1hr 56mins','the-man-from-uncle.jpg');
INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (11,'spectre','Spectre','A cryptic message from Bond''s past sends him on a trail to uncover a sinister organization. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind SPECTRE.','action,adventure,thriller',6.9,'2hr 28mins','spectre.jpg');
INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (12,'legend','Legend','The film tells the story of the identical twin gangsters Reggie and Ronnie Kray, two of the most notorious criminals in British history, and their organised crime empire in the East End of London during the 1960s.','biography,crime,drama',7.0,'2hr 28mins','legend.jpg');
INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (13,'southpaw','Southpaw','Boxer Billy Hope turns to trainer Tick Wills to help him get his life back on track after losing his wife in a tragic accident and his daughter to child protection services.','action,drama,sport',7.5,'2hr 4mins','southpaw.jpg');
INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (14,'bridge-of-spies','Bridge of Spies','During the Cold War, an American lawyer is recruited to defend an arrested Soviet spy in court, and then help the CIA facilitate an exchange of the spy for the Soviet captured American U2 spy plane pilot, Francis Gary Powers.','biography,drama,thriller',7.7,'2hr 22mins','bridge-of-spies.jpg');
INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (15,'ant-man','Ant-Man','Armed with a super-suit with the astonishing ability to shrink in scale but increase in strength, cat burglar Scott Lang must embrace his inner hero and help his mentor, Dr. Hank Pym, plan and pull off a heist that will save the world.','action,adventure,scifi',7.4,'1hr 57mins','ant-man.jpg');
INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (16,'fast-and-furious-7','Fast & Furious 7','Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.','action,crime,thriller',7.3,'2hr 17mins','fast-and-furious-7.jpg');
INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (17,'tracers','Tracers','Wanted by the Chinese mafia, a New York City bike messenger escapes into the world of parkour after meeting a beautiful stranger.','action,crime,drama',5.6,'1hr 34mins','tracers.jpg');
INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (18,'running-scared','Running Scared','A low-ranking thug is entrusted by his crime boss to dispose of a gun that killed corrupt cops, but things get out of control when the gun ends up in wrong hands.','action,crime,drama',7.4,'2hr 2mins','running-scared.jpg');
INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (19,'the-hangover','The Hangover','Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing. They make their way around the city in order to find their friend before his wedding.','comedy',7.8,'1hr 40mins','the-hangover.jpg');
INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (20,'project-x','Project X','3 high school seniors throw a birthday party to make a name for themselves. As the night progresses, things spiral out of control as word of the party spreads.','comedy,crime',6.7,'1hr 28mins','project-x.jpg');
INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (21,'the-dark-knight','The Dark Knight','When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the caped crusader must come to terms with one of the greatest psychological tests of his ability to fight injustice.','action,crime,drama',9.0,'2hr 32mins','the-dark-knight.jpg');
INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (22,'the-tournament','The Tournament','Every seven years in an unsuspecting town, The Tournament takes place. A battle royale between 30 of the world''s deadliest assassins. The last man standing receiving the $10,000,000 cash prize and the title of Worlds No 1, which itself carries the legendary million dollar a bullet price tag.','action,thriller',6.1,'1hr 35mins','the-tounament.jpg');
INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (23,'the-matrix','The Matrix','A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.','action,scifi',8.7,'2hr 16mins','the-matrix.jpg');
INSERT INTO movies(id,slug,name,description,genres,rate,length,img) VALUES (24,'bad-boys','Bad Boys','Two hip detectives protect a murder witness while investigating a case of stolen heroin.','action,comedy,crime',6.8,'1hr 59mins','bad-boys.jpg');


